[Brewfile] Fix issues for `brew bundle`. Add a few missing brews.
Warning: handbrake was renamed to handbrake-app
Error: No apps found in the Mac App Store for app ID 405399194
Installing Kindle has failed!
Error: No apps found in the Mac App Store for app ID 926036361
Installing LastPass has failed!
Installing vagrant-completion has failed!
Installing dog has failed!